# Folder to pull files from
origin_folder: "D:/TEST/downloads"

parameters:
  active_mode: "video_editing"
  retry_time: 1.0 # Time to wait between moving attempts. Should be because the file is still being written to disk
  attempt_limit: 60 # Times to attempt to move the file. Just in case the program enters an infinite loop
  convert_webp_to_png: True

# Groups of file extension to organize into folders by category
extension_groups:

  image:
    extensions: [".jpg", ".jpeg", ".png", ".webp"]
    destination: "D:/TEST/destination/imgs"

  video:
    extensions: [".mov", ".mp4", ".mkv"]
    destination: "D:/TEST/destination/vids"

  document:
    extensions: [".txt", ".pdf", ".docx"]
    destination: "D:/TEST/destination/docs"

  audio:
    extensions: [".mp3", ".flac", ".wav"]
    destination: "D:/TEST/destination/music"


modes:
  default:
    display_name: "Default"
    icon: "./view-search-eye-human-eye-899760.ico"
    shortcut: "ctrl+alt+shift+9"

  video_editing:
    display_name: "Video Editing"
    icon: "./icons8-library-64.ico"
    shortcut: "ctrl+alt+shift+8"
    override_groups:
        image: "D:/TEST/override/img"
        video: "D:/TEST/override/vid"
  
  pumpkin_farming:
    override_groups: Null
    rolf: "lol"
