# Folder to listen for new files (downloads)
# Example: "C:/Users/SomeUser/Downloads"
origin_folder: "path/to/folder"

# General settings
parameters:
  retry_time: 1.0 # Time in seconds to wait between moving attempts. Should be because the file is still being written to disk.
  attempt_limit: 60 # Times to attempt to move the file. Just in case the program enters an infinite loop.
  convert_webp_to_png: False # (True/False) Whether to convert WEBP files to PNG or not. As currently implemented, if True, WebP file will be deleted after conversion.

# Groups of file extension to organize into folders by category.
# Add and change groups to your liking.
# Use Linux style paths with "/" or as an alternative "\\"
# Example: "C:/Users/SomeUser/Pictures"
extension_groups:

  images:
    extensions: [".jpg", ".jpeg", ".png", ".webp"]
    destination: "path/to/folder"
  
  icons:
    extensions: [".ico"]
    destination: "path/to/folder"

  videos:
    extensions: [".mov", ".mp4", ".mkv"]
    destination: "path/to/folder"

  documents:
    extensions: [".txt", ".pdf", ".docx", ".epub"]
    destination: "path/to/folder"

  audio:
    extensions: [".mp3", ".flac", ".wav"]
    destination: "path/to/folder"
  

# 'Modes' to override the destination directories for certain groups.
# Create an 'override_groups' key in any new mode and match the name of any group above to override their destination path.
modes:
  # You can change the values from the 'default' mode, but deleting the keys (display_name, icon, shortcut), is likely to lead to errors.
  default:
    display_name: "Default"
    icon: "download.ico"
    shortcut: "ctrl+alt+shift+9"

  # Here you can add any new modes to your liking. With these, none of the keys should be essential.
  # Make sure the names of the override_groups match the desired name of the group to overwrite.
  video_editing:
    display_name: "Video Editing"
    icon: "start.ico"
    shortcut: "ctrl+alt+shift+8"
    override_groups:
        images: "path/to/override/folder"
        videos: "path/to/override/folder"